name: Use the Composite Action with Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Do anything elsee
        run: echo Pretend to do other things 

      # Uses the Composite Action
      - name: Build and Push the image
        uses: n3wt0n/CompositeAction@main
        with:
          registry_username: ${{secrets.REGISTRY_USERNAME}}
          registry_password: ${{secrets.REGISTRY_PASSWORD}}
          image_name: my-awesome-app
          tag: $GITHUB_RUN_NUMBER
