# This is a basic workflow to help you get started with Actions

name: Issue - Responder

# Controls when the action will run. 
on:
  issues:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      #- name: Get Version
      #  run: |         
      #    $str=(${{ github.event.issue.body }} | grep Version:)
      #    echo "VERSION=$str" >> $GITHUB_ENV
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: contains(github.event.issue.labels.*.name, 'deployment')
        run: echo Version is ${{ github.event.issue.body }}

      
