name: Try Log Secrets

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
    
     
     

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - name: Log the secret
        run: echo ${{ secrets.MY_SECRET}}

