name: Inactive Users

on:
  workflow_dispatch:

jobs:
  retrieve:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Organization User Activity Report
        uses: peter-murray/inactive-users-action@v1
        with:
          token: ${{ secrets.PSATOKEN }} 
          outputDir:  ${{ github.workspace }}
          organization: playstudios
          # The number of days in the past to check for activity, this will be ignored if 'since' parameter is used.
          activity_days: 90
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Report
          path: ${{ github.workspace }}/organization_user_activity.csv
