name: UploadDownload

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |-
            **/target/*.jar
            anotherfile.txt
            !**.log 
            
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact   
